import { 
  Home, 
  LayoutDashboard, 
  Settings, 
  Search, 
  Plus, 
  Trash2, 
  Edit2, 
  Download, 
  Filter, 
  Camera, 
  Languages,
  Users,
  User,
  Shield,
  UserPlus, 
  ToggleRight,
  Eye, 
  EyeOff,
  UserCog,
  CheckCircle2,
  FileText,
  ClipboardList,
  BarChart3,
  Activity,
  Star,
  Bell,
  Mail,
  MessageSquare,
  Disc,
  CreditCard,
  Archive,
  AlertTriangle,
  MoreHorizontal,
  Printer,
  ArrowRightLeft,
  History,
  Database,
  ArrowDown,
  AlertCircle,
  FolderOpen,
  Clock,
  Timer,
  X,
  Calendar,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  RefreshCw,
  LogOut,
  Moon,
  Sun,
  TrendingUp,
  TrendingDown,
  Save,
  Menu,
  Hash,
  Hospital
} from 'lucide-react';

export const COLORS = {
  primary: '#0056b3', 
  secondary: '#E3F2FD', 
  background: '#FFFFFF', 
  text: '#2C3E50', 
  status: {
    Hold: '#FEF3C7',
    Tarek: '#E5E7EB',
    CD: '#FFEDD5',
    Payment: '#FEE2E2',
    Saving: '#DCFCE7',
    Setup: '#E0E7FF',
    Finished: '#CFFAFE'
  }
};

export const STATUS_CLASSES = {
  Hold: 'bg-amber-50 text-amber-800 border-amber-200 shadow-sm',
  Tarek: 'bg-slate-50 text-slate-800 border-slate-200 shadow-sm',
  CD: 'bg-orange-50 text-orange-800 border-orange-200 shadow-sm',
  Payment: 'bg-rose-50 text-rose-800 border-rose-200 shadow-sm',
  Saving: 'bg-emerald-50 text-emerald-800 border-emerald-200 shadow-sm',
  Setup: 'bg-indigo-50 text-indigo-800 border-indigo-200 shadow-sm',
  Finished: 'bg-cyan-50 text-cyan-800 border-cyan-200 shadow-sm'
};

export const ICONS = {
  Home,
  LayoutDashboard,
  Settings,
  Search,
  Plus,
  Trash2,
  Edit2,
  Download,
  Filter,
  Camera,
  Languages,
  Users,
  Shield,
  UserPlus,
  ToggleRight,
  Eye,
  EyeOff,
  UserCog,
  CheckCircle: CheckCircle2,
  FileText,
  Register: ClipboardList,
  BarChart: BarChart3,
  Activity,
  Star,
  Bell,
  Mail,
  MessageSquare,
  Disc,
  CreditCard,
  Archive,
  AlertTriangle,
  MoreHorizontal,
  Printer,
  ArrowRightLeft,
  History,
  Database,
  ArrowDown,
  AlertCircle,
  FolderOpen,
  Clock,
  Timer,
  X,
  Calendar,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  Refresh: RefreshCw,
  LogOut,
  Moon,
  Sun,
  TrendingUp,
  TrendingDown,
  Save,
  Menu,
  User,
  Hash,
  Hospital
};